default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: deploy_rp_development

test:
  <<: *default
  database: deploy_rp_test

production:
  <<: *default
  database: deploy_rp_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
